(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }})("Box2D",
{ "height":24,
 "layers":[
        {
         "draworder":"topdown",
         "height":32,
         "name":"Box2D",
         "objects":[
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":1024,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":1024,
                 "x":0,
                 "y":736
                }, 
                {
                 "height":704,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":0,
                 "y":32
                }, 
                {
                 "height":704,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":992,
                 "y":32
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-32,
                         "y":32
                        }, 
                        {
                         "x":-32,
                         "y":64
                        }, 
                        {
                         "x":0,
                         "y":96
                        }, 
                        {
                         "x":32,
                         "y":96
                        }, 
                        {
                         "x":64,
                         "y":64
                        }, 
                        {
                         "x":64,
                         "y":32
                        }, 
                        {
                         "x":32,
                         "y":0
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"Poly",
                 "visible":true,
                 "width":0,
                 "x":288,
                 "y":288
                }, 
                {
                 "height":0,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":128,
                         "y":-64
                        }, 
                        {
                         "x":288,
                         "y":-96
                        }, 
                        {
                         "x":512,
                         "y":-64
                        }, 
                        {
                         "x":704,
                         "y":32
                        }, 
                        {
                         "x":800,
                         "y":96
                        }, 
                        {
                         "x":832,
                         "y":128
                        }, 
                        {
                         "x":0,
                         "y":128
                        }],
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"Ground",
                 "visible":true,
                 "width":0,
                 "x":32,
                 "y":608
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "renderorder":"right-down",
 "tileheight":32,
 "tilesets":[],
 "tilewidth":32,
 "version":1,
 "width":32
});